#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<stdbool.h>

bool check(const char *);
unsigned char enc_flag[] = {0xb8, 0xa3, 0x64, 0xb8, 0xbd, 0xb4, 0x98, 0xf3, 0x7d, 0x8c, 0xa8, 0xa6, 0x65, 0xa7, 0xf0, 0x3c, 0x9d, 0x8d, 0xcf, 0x1b, 0x63, 0x8, 0x7b, 0xe7, 0x7e, 0xf2, 0x8f, 0x98, 0xba, 0xd6, 0x53, 0xdb, 0x17, 0xd4, 0xf9, 0xfb, 0x93, 0x95, 0x3c, 0x1f, 0x7c, 0xfb, 0x89, 0x31, 0x9a, 0xb2, 0x8};
//ACTF{idapython_is_a_efftive_tool_for_reversing}
//len = 0x2f
int main(){
    puts("do you know the idapython?");
    puts("please Input");
    char buffer[0x200];
    scanf("%s", buffer);
    if(check(buffer)){
        puts("success!");
    }
    else{
        puts("fail");
    }
    system("pause");
    return 0;
}

bool check(const char* target){
    unsigned char *buffer = (unsigned char *)malloc(0x100);
    memcpy(buffer, target, strlen(target));
    buffer[strlen(target)] = '\0';
    asm(
        "mov al,[rdx+0]\n"\
        "add al,12\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,249\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,198\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,246\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,71\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,97\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,203\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,194\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,176\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,111\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,37\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,73\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,65\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,204\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,231\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,228\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,39\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,192\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,119\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,30\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,231\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,105\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,7\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,37\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,232\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,136\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,32\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,182\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,108\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,251\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,50\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,123\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,23\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,176\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,205\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,76\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,141\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,182\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,193\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,201\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,122\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,0\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,196\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,184\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,207\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,15\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,46\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,21\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,166\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,37\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,33\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,134\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,166\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,129\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,54\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,111\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,25\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,202\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,158\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,1\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,168\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,146\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,121\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,171\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,113\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,189\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,50\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,105\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,45\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,110\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,72\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,123\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,64\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,198\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,60\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,34\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,100\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,126\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,43\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,196\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,39\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,92\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,158\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,92\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,144\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,55\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,85\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,53\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,34\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,205\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,92\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,136\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,224\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,82\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,102\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,19\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,169\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,124\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,218\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,216\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,204\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,159\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,112\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,46\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,118\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,119\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,83\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,190\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,114\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,50\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,60\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,117\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,71\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,113\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,77\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,99\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,40\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,91\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,87\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,169\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,230\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,229\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,227\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,206\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,215\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,116\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,22\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,179\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,43\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,138\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,71\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,165\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,81\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,111\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,15\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,35\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,228\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,131\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,98\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,227\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,3\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,10\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,180\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,23\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,224\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,253\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,98\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,188\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,91\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,236\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,62\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,231\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,23\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,19\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,240\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,69\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,58\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,165\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,246\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,164\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,249\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,146\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,230\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,208\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,202\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,211\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,81\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,133\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,222\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,16\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,43\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,185\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,118\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,193\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,15\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,32\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,252\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,236\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,206\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,198\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,52\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,20\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,94\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,62\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,242\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,73\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,150\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,38\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,87\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,41\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,118\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,138\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,230\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,223\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,34\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,193\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,132\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,5\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,92\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,17\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,226\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,25\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,159\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,187\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,223\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,41\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,187\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,38\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,171\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,197\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,81\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,0\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,157\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,245\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,118\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,97\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,47\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,189\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,160\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,225\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,141\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,85\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,181\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,214\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,40\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,38\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,201\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,56\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,168\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,95\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,33\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,188\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,149\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,162\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,48\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,102\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,77\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,25\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,94\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,48\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,239\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,39\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,196\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,219\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,165\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,220\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,136\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,73\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,212\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,169\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,165\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,180\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,92\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,63\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,41\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,215\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,105\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,111\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,250\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,160\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,189\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,225\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,186\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,32\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,164\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,243\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,40\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,21\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,56\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,53\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,195\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,183\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,106\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,8\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,175\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,208\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,214\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,32\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,84\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,183\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,129\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,68\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,99\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,37\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,244\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,148\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,168\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,17\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,53\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,109\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,108\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,170\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,18\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,252\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,23\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,55\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,166\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,212\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,88\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,72\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,247\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,75\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,173\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,79\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,210\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,168\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,35\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,91\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,72\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,250\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,128\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,98\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,22\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,251\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,11\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,239\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,68\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,160\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,64\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,43\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,65\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,223\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,161\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,13\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,227\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,92\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,162\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,231\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,28\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,62\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,6\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,33\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,131\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,155\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,202\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,99\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,108\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,31\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,104\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,53\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,11\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,25\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,20\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,172\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,92\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,222\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,131\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,47\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,207\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,140\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,180\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,22\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,64\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,158\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,254\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,171\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,189\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,121\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,236\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,41\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,206\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,135\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,211\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,178\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,124\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,133\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,105\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,118\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,86\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,81\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,51\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,199\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,120\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,152\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,253\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,21\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,32\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,120\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,231\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,200\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,23\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,28\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,51\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,1\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,144\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,191\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,149\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,179\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,215\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,119\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,17\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,136\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,149\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,12\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,43\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,145\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,55\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,107\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,244\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,176\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,201\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,48\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,126\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,163\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,187\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,188\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,10\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,1\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,186\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,169\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,204\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,121\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,153\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,168\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,241\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,127\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,78\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,190\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,87\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,210\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,175\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,126\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,3\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,193\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,187\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,12\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,177\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,27\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,104\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,175\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,220\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,121\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,5\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,156\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,10\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,32\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,82\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,211\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,248\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,56\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,189\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,219\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,30\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,162\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,115\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,208\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,63\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,252\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,138\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,239\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,93\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,74\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,69\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,131\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,24\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,143\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,86\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,109\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,110\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,14\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,196\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,233\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,127\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,228\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,153\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,123\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,228\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,244\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,230\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,192\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,23\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,207\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,8\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,19\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,174\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,8\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,155\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,207\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,102\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,11\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,86\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,102\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,45\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,101\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,113\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,82\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,216\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,63\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,233\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,73\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,93\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,202\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,210\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,53\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,54\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,124\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,185\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,124\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,124\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,217\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,119\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,245\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,202\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,184\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,58\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,118\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,238\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,199\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,150\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,60\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,178\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,79\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,13\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,134\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,219\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,27\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,43\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,137\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,113\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,102\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,130\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,61\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,126\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,101\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,202\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,113\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,208\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,202\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,150\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,43\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,143\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,17\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,148\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,85\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,227\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,238\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,210\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,37\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,215\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,154\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,19\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,15\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,41\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,219\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,183\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,31\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,156\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,84\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,208\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,117\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,201\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,153\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,225\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,22\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,96\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,182\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,196\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,15\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,69\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,74\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,180\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,170\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,239\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,119\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,138\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,209\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,81\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,206\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,197\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,94\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,224\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,38\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,95\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,160\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,117\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,30\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,245\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,146\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,185\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,112\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,92\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,220\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,208\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,105\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,74\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,34\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,89\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,221\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,12\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,234\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,134\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,243\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,59\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,210\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,107\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,167\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,179\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,226\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,36\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,207\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,49\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,199\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,210\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,175\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,127\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,68\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,124\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,19\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,176\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,117\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,204\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,142\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,74\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,2\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,120\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,118\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,147\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,236\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,23\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,86\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,171\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,22\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,66\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,245\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,28\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,85\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,94\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,30\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,17\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,122\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,178\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,218\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,86\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,227\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,113\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,54\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,58\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,46\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,37\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,54\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,115\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,171\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,190\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,61\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,126\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,85\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,159\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,115\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,205\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,18\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,16\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,124\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,214\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,215\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,7\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,79\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,83\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,226\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,107\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,81\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,220\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,246\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,123\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,229\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,207\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,136\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,138\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,31\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,41\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,99\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,164\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,121\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,149\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,83\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,2\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,134\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,86\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,223\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,23\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,199\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,185\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,52\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,236\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,31\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,81\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,240\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,112\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,51\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,18\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,131\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,240\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,45\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,230\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,74\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,196\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,242\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,187\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,11\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,204\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,163\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,8\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,71\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,13\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,82\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,203\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,236\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,175\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,109\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,116\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,58\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,160\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,31\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,144\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,165\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,197\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,128\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,135\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,34\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,205\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,207\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,180\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,251\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,3\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,113\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,3\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,98\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,55\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,64\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,81\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,116\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,114\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,165\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,247\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,81\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,183\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,71\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,77\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,30\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,222\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,37\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,175\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,248\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,85\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,54\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,211\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,124\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,172\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,148\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,28\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,37\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,57\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,73\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,22\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,61\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,19\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,73\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,2\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,105\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,133\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,215\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,58\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,225\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,20\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,222\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,203\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,16\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,2\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,191\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+12]\n"\
        "add al,1\n"\
        "mov [rdx+12],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,114\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,35\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,215\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,80\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,112\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,34\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,104\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,67\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,116\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,236\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,126\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,78\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,14\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,179\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,45\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,56\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,91\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,212\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,95\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,15\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,171\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,143\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,96\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,87\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,76\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,233\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,254\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,218\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,74\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,134\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,219\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,74\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,119\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,102\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,18\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,194\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,170\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,39\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,92\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,175\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,123\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,207\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,132\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,225\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,9\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,103\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,31\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,112\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,61\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,11\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,93\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,160\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,184\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,252\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,140\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,187\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,42\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,211\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,106\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,38\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,42\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,223\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,110\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,6\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,70\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,40\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,37\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,131\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,59\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,108\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,216\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,29\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,151\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,53\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,160\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,144\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,33\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,194\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,148\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,85\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,121\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,208\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,229\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,10\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,60\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,5\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,39\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,28\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+45]\n"\
        "add al,153\n"\
        "mov [rdx+45],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,127\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+31]\n"\
        "add al,254\n"\
        "mov [rdx+31],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,202\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,59\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,4\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,39\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,152\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,87\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,154\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,159\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,214\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,172\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,174\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+16]\n"\
        "add al,20\n"\
        "mov [rdx+16],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,101\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,33\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,191\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,46\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,89\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,229\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,7\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,249\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,252\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,166\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,171\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,92\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,224\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,14\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,132\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,214\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,234\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,31\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,28\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,244\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,199\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,124\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,54\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,71\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,228\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,208\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+5]\n"\
        "add al,117\n"\
        "mov [rdx+5],al\n"\
        "mov al,[rdx+20]\n"\
        "add al,96\n"\
        "mov [rdx+20],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,78\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,96\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,75\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,62\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,153\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,229\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,95\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,18\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+2]\n"\
        "add al,121\n"\
        "mov [rdx+2],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,108\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,130\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,14\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,89\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,184\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,188\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,49\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+29]\n"\
        "add al,192\n"\
        "mov [rdx+29],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,75\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,44\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,145\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,160\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,13\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+7]\n"\
        "add al,171\n"\
        "mov [rdx+7],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,33\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,152\n"\
        "mov [rdx+11],al\n"\
        "mov al,[rdx+35]\n"\
        "add al,206\n"\
        "mov [rdx+35],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,107\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,138\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,117\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,190\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,188\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,115\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,36\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,57\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,62\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,74\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,143\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,187\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,225\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+17]\n"\
        "add al,97\n"\
        "mov [rdx+17],al\n"\
        "mov al,[rdx+32]\n"\
        "add al,130\n"\
        "mov [rdx+32],al\n"\
        "mov al,[rdx+10]\n"\
        "add al,88\n"\
        "mov [rdx+10],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,13\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,84\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+6]\n"\
        "add al,113\n"\
        "mov [rdx+6],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,137\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+19]\n"\
        "add al,39\n"\
        "mov [rdx+19],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,124\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+43]\n"\
        "add al,18\n"\
        "mov [rdx+43],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,59\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+15]\n"\
        "add al,206\n"\
        "mov [rdx+15],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,23\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,30\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+46]\n"\
        "add al,216\n"\
        "mov [rdx+46],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,12\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+21]\n"\
        "add al,189\n"\
        "mov [rdx+21],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,174\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,62\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,125\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+41]\n"\
        "add al,113\n"\
        "mov [rdx+41],al\n"\
        "mov al,[rdx+38]\n"\
        "add al,74\n"\
        "mov [rdx+38],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,143\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,91\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,40\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,5\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+28]\n"\
        "add al,53\n"\
        "mov [rdx+28],al\n"\
        "mov al,[rdx+44]\n"\
        "add al,75\n"\
        "mov [rdx+44],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,120\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,84\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,146\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+37]\n"\
        "add al,223\n"\
        "mov [rdx+37],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,180\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+14]\n"\
        "add al,101\n"\
        "mov [rdx+14],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,234\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+22]\n"\
        "add al,154\n"\
        "mov [rdx+22],al\n"\
        "mov al,[rdx+24]\n"\
        "add al,245\n"\
        "mov [rdx+24],al\n"\
        "mov al,[rdx+25]\n"\
        "add al,65\n"\
        "mov [rdx+25],al\n"\
        "mov al,[rdx+9]\n"\
        "add al,135\n"\
        "mov [rdx+9],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,22\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+30]\n"\
        "add al,56\n"\
        "mov [rdx+30],al\n"\
        "mov al,[rdx+39]\n"\
        "add al,85\n"\
        "mov [rdx+39],al\n"\
        "mov al,[rdx+23]\n"\
        "add al,227\n"\
        "mov [rdx+23],al\n"\
        "mov al,[rdx+33]\n"\
        "add al,201\n"\
        "mov [rdx+33],al\n"\
        "mov al,[rdx+27]\n"\
        "add al,11\n"\
        "mov [rdx+27],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,136\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+26]\n"\
        "add al,183\n"\
        "mov [rdx+26],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,187\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+13]\n"\
        "add al,175\n"\
        "mov [rdx+13],al\n"\
        "mov al,[rdx+42]\n"\
        "add al,226\n"\
        "mov [rdx+42],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,102\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+36]\n"\
        "add al,88\n"\
        "mov [rdx+36],al\n"\
        "mov al,[rdx+34]\n"\
        "add al,171\n"\
        "mov [rdx+34],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,213\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,63\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+8]\n"\
        "add al,165\n"\
        "mov [rdx+8],al\n"\
        "mov al,[rdx+18]\n"\
        "add al,186\n"\
        "mov [rdx+18],al\n"\
        "mov al,[rdx+3]\n"\
        "add al,198\n"\
        "mov [rdx+3],al\n"\
        "mov al,[rdx+1]\n"\
        "add al,67\n"\
        "mov [rdx+1],al\n"\
        "mov al,[rdx+0]\n"\
        "add al,239\n"\
        "mov [rdx+0],al\n"\
        "mov al,[rdx+40]\n"\
        "add al,225\n"\
        "mov [rdx+40],al\n"\
        "mov al,[rdx+4]\n"\
        "add al,114\n"\
        "mov [rdx+4],al\n"\
        "mov al,[rdx+11]\n"\
        "add al,101\n"\
        "mov [rdx+11],al\n"\
        :
        :"d"(buffer)\
    );
    if(memcmp(buffer,enc_flag,0x2f)){
            free(buffer);
            return false;
    }
    free(buffer);
    return true;
}